### ISSUE TITLE
Option to run code on terminal doesn't show up

### ISSUE THREAD

**Issue by Gr-Nobel** [JameelKaisar/Competitive-Programming-Lite#2]
![image](https://user-images.githubusercontent.com/95166364/203685533-294cc1f9-27ab-4b5e-bcfa-4552262a2bb9.png)
after opening a problem typing out solution and everything the running code on terminal doesn't show up.

**Comment by jameelkaisar** [comment]
You mean the Context Menu entries are missing? Actually I was suggested to drop the context menu entries in this [pr](https://github.com/wbond/package_control_channel/pull/8462#issuecomment-1092073069). I have mentioned this in [v1.2.0 release notes](https://github.com/JameelKaisar/Competitive-Programming-Lite/releases/tag/v1.2.0).

**Comment by Gr-Nobel** [comment]
I was following the video in readme file.
